-- Reproducible baseline for clean environments. Every object is idempotent so
-- this can also be adopted by the existing hosted project whose first schema
-- migrations predated source control.
create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  domain text not null unique,
  sector text,
  country text,
  size_band text,
  first_scanned_at timestamptz,
  last_scanned_at timestamptz,
  created_at timestamptz not null default now(),
  is_seed boolean not null default false,
  opt_out boolean not null default false
);

create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites(id) on delete cascade,
  slug text not null,
  rubric_version text not null,
  status text not null check (status in ('queued', 'running', 'complete', 'failed')),
  started_at timestamptz,
  completed_at timestamptz,
  rung smallint check (rung between 0 and 4),
  composite numeric,
  d1 numeric,
  d2 numeric,
  d3 numeric,
  d4 numeric,
  d5 numeric,
  trigger text not null check (trigger in ('user', 'seed', 'rescan', 'agent')),
  requester_type text not null check (requester_type in ('human', 'agent')),
  user_agent text,
  error text,
  created_at timestamptz not null default now(),
  requester_ip_hash text
);

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.scans(id) on delete cascade,
  dimension text not null check (dimension in ('D1', 'D2', 'D3', 'D4', 'D5')),
  signal_key text not null,
  value_bool boolean,
  value_num numeric,
  value_text text,
  evidence_url text not null,
  evidence_snippet text check (char_length(evidence_snippet) <= 500),
  observed_at timestamptz not null
);

create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.scans(id) on delete cascade,
  rank smallint not null,
  template_key text not null,
  rendered_text text not null,
  impact smallint not null,
  ease smallint not null
);

create table if not exists public.agent_hits (
  id bigint generated by default as identity primary key,
  scan_id bigint references public.scans(id) on delete set null,
  tool_name text not null,
  arguments_json jsonb,
  agent_ua text,
  outcome text not null,
  at timestamptz not null default now()
);

create table if not exists public.rubric_versions (
  version text primary key,
  published_at timestamptz not null,
  weights_json jsonb not null,
  changelog text
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null,
  domain text not null,
  scan_id bigint references public.scans(id) on delete set null,
  ip_hash text,
  report_sent boolean not null default false,
  unsubscribed boolean not null default false,
  created_at timestamptz not null default now(),
  send_error text,
  unique (email, domain)
);

create table if not exists public.scan_queue (
  id bigint generated by default as identity primary key,
  domain text not null unique,
  sector text,
  status text not null default 'pending' check (status in ('pending', 'running', 'done', 'failed')),
  attempts integer not null default 0,
  error text,
  queued_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  event_kind text not null,
  requester_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists scans_site_completed_idx
  on public.scans (site_id, completed_at desc) where status = 'complete';
create index if not exists scans_complete_created_idx
  on public.scans (created_at desc) where status = 'complete';
create index if not exists scans_slug_created_idx on public.scans (slug, created_at desc);
create index if not exists scans_ip_hash_recent on public.scans (requester_ip_hash, created_at desc)
  where requester_ip_hash is not null;
create index if not exists signals_scan_id_idx on public.signals (scan_id);
create index if not exists opportunities_scan_rank_idx on public.opportunities (scan_id, rank);
create index if not exists leads_ip_recent_idx on public.leads (ip_hash, created_at desc)
  where ip_hash is not null;
create index if not exists scan_queue_pending_claim_idx
  on public.scan_queue (id) where status = 'pending' and attempts < 3;
create index if not exists rate_limit_events_lookup_idx
  on public.rate_limit_events (event_kind, requester_hash, created_at desc);

alter table public.sites enable row level security;
alter table public.scans enable row level security;
alter table public.signals enable row level security;
alter table public.opportunities enable row level security;
alter table public.agent_hits enable row level security;
alter table public.rubric_versions enable row level security;
alter table public.leads enable row level security;
alter table public.scan_queue enable row level security;
alter table public.rate_limit_events enable row level security;

insert into public.rubric_versions (version, published_at, weights_json, changelog)
values (
  '1.0.0',
  now(),
  '{"weights":{"d1":0.25,"d2":0.30,"d3":0.20,"d4":0.15,"d5":0.10},"gates":{"readable_d1_min":40,"answerable_d2_min":50,"blocked_bots_invisible":3}}'::jsonb,
  'Initial published Agent Surface Ladder rubric.'
)
on conflict (version) do nothing;
